#!/bin/sh

#put controller.png where it goes

VBA_HOME=/media/internal/vba
SKINS=$VBA_HOME/skins

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
fi

rm -f $CONTROLLER
mkdir -p $VBA_HOME
#while we're at it...
mkdir -p $VBA_HOME/roms

#copy the controller.png over
cp -r $IPKG_OFFLINE_ROOT/$SKINS $SKINS

exit 0`
