#!/bin/sh

#put controller.png where it goes

VBA_HOME=/media/internal/vba
SKINS=$VBA_HOME/skins

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
fi

mkdir -p $VBA_HOME
#while we're at it...
mkdir -p $VBA_HOME/roms
#remove old skins directory...
rm -rf $SKINS
#create it again
mkdir -p $SKINS

#extract the skins tar
tar xf $IPKG_OFFLINE_ROOT/$SKINS/skins.tar -C $SKINS

exit 0
